# 1. Add/Substract/Multiplay/div/pow

## 1.1  Array with scalar (value)

In [8]:
import numpy as np 

array_1_d = np.array([1,2, 3, 4])

"""
Addition 
"""
print("a initially :\n", a)
print()
print('a + 1 for each element :\n', array_1_d+1)
print()
print("a -1 for each element :\n", array_1_d-1)
print()
print("a/2 for each element :\n", array_1_d/2)
print()
print("a*2 for each element :\n", array_1_d*2)
print()
print("a**2 for each element :\n", array_1_d**2)

a initially :
 [1, 3, 4]

a + 1 for each element :
 [2 3 4 5]

a -1 for each element :
 [0 1 2 3]

a/2 for each element :
 [0.5 1.  1.5 2. ]

a*2 for each element :
 [2 4 6 8]

a**2 for each element :
 [ 1  4  9 16]


## 1.2 Array with array

In [11]:
array_1_d = np.array([1,2, 3, 4])
array_1_2_d = np.array([1,2, 3, 4])

print("arrays are : \n", array_1_2_d, "\n", array_1_d)
print()

print('a + b :\n', array_1_d+array_1_2_d)
print()
print('a - b :\n', array_1_d-array_1_2_d)
print()
print('a / b :\n', array_1_d/array_1_2_d)
print()
print('a * b :\n', array_1_d*array_1_2_d)


arrays are : 
 [1 2 3 4] 
 [1 2 3 4]

a + b :
 [2 4 6 8]

a - b :
 [0 0 0 0]

a / b :
 [1. 1. 1. 1.]

a * b :
 [ 1  4  9 16]


# 2. Mathematic transformation

In [19]:
print("array_1_d :\n", array_1_d)
print("arr_1_2_d : \n", array_1_2_d)
cos_np = np.cos(array_1_d)
print("cos transformation : \n", cos_np)
sin_np = np.sin(array_1_d)
print("sin transformation : \n", sin_np)

print()


"""
transformation with two numpy array
"""
mat_mul_np = np.matmul(array_1_d, array_1_2_d)
print("matmul transformation : \n", mat_mul_np)

"""
Find determinant 
"""
identity_2_d = np.identity(3)
print("deteminant is : \n", np.linalg.det(identity_2_d))

array_1_d :
 [1 2 3 4]
arr_1_2_d : 
 [1 2 3 4]
cos transformation : 
 [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
sin transformation : 
 [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]

matmul transformation : 
 30
deteminant is : 
 1.0


# 3. Statistics

In [24]:
"""
min 
"""

print("array : \n", array_2_d)
print()
print("min array : ", np.min(array_2_d))

"""
max
"""
print("max array : ", np.max(array_2_d))
print()
"""
sum
"""
print("sum array : ", np.sum(array_2_d))
print("sum on axis 0 array : ", np.sum(array_2_d, axis=0))
print("sum on axis 1 array : ", np.sum(array_2_d, axis=1))

array : 
 [[ 1 34 22]
 [ 2  8  3]]

min array :  1
max array :  34

sum array :  70
sum on axis 0 array :  [ 3 42 25]
sum on axis 1 array :  [57 13]
